# ==========================================
# PRISMA STUDIO DOCKERFILE
# ==========================================
FROM node:24-lts-alpine
WORKDIR /app

COPY package.json package-lock.json* ./
RUN npm install --omit=dev

COPY prisma ./prisma

ENV PORT=5555
EXPOSE 5555

CMD ["npx", "prisma", "studio", "--port", "5555", "--browser", "none"]